// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgyvdvrdnzyoxapinkxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneXZkdnJkbnp5b3hhcGlua3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjY2NDksImV4cCI6MjA2NzY0MjY0OX0.Gj4yLLEvZ23cMpGy_KZ4-RGFaF17tVSXheZzfy--8y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});